### ISSUE TITLE
Changes to imported sass files don't trigger a recompile

### ISSUE THREAD

**Issue by taylorsmith** [anaisbetts/SassAndCoffee#29] opened 2011-11-11 22:19 UTC
In `application.scss` I'm importing a bunch of partials: `_screen.scss`, `_mobile.scss`, `_ie.scss`, and `_print.scss`. Within my markup, I'm only referencing `application.css`. This works well until I make a change to any of the partials. The CSS only seems to be recompiled when a change to `application.scss` is detected.

**Comment by anaisbetts** [comment] 2011-11-18 04:50
This is a dupe of #12

**Closed as completed by anaisbetts** 2011-11-18 04:50 UTC
